bugtracker/Controllers/BugController.cs
using bugtracker.Data;
using bugtracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace bugtracker.Controllers
{   

    public class BugController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly ApplicationDbContext _database;

        public BugController(ApplicationDbContext database, UserManager<IdentityUser> userManager)
        {
            _database = database;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //getting Data from BugDatabase (Backend) to display on the website via ViewBag
            var bugs = _database.BugDatabase.ToList();
            ViewBag.CurrentBugs = bugs;

            return View();
        }

        [HttpGet]
        public IActionResult ClosedBugs()
        {
            var bugs = _database.BugDatabase.ToList();
            ViewBag.CurrentBugs = bugs;

            return View();
        }

        [HttpGet]
        public IActionResult BugHistory()
        {
            return View();
        }


        [Authorize (Roles = "User,Admin")]
        public IActionResult CreateBug(int id)
        {
            //create new Bug
            if (id == 0)
            {
                return View("BugVerwaltung");
            }

            var bug = _database.BugDatabase.Find(id);
           
            //bug not found, because off Link manipulation
            if (bug == null)
            {
                return View("NotFound");
            }

            //edit existing bug
            return View("BugVerwaltung",bug);
        }

        [HttpPost] 
        public IActionResult BugVerwaltung(Bug bug)
        {
            if (bug.Status == null) bug.Status = "open";
            if (bug.Priority == null) bug.Priority = "low";
            if (bug.Category == null) bug.Category = "other";
            if (bug.Details == null) bug.Details = "no additional information was given";

            _database.BugDatabase.Update(bug);
            _database.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize (Roles = "Admin")]
        public IActionResult DeleteBug(Bug bug)
        {
            _database.BugDatabase.Remove(bug);
            _database.SaveChanges();
            return RedirectToAction("Index"); //return View doesnt render the page, any changes made would not be shown!
        }

        public IActionResult DetailedBugOverview(int id)
        {
            var bug = _database.BugDatabase.Find(id);
            ViewData["Message"] = $" View bug: {id}" ;

            if (bug == null)
            {
                return View("NotFound");
            }

            ViewBag.CurrentBug = bug;
            return View("DetailedBugOverview", bug);
        }

        [HttpPost]
        public IActionResult AssignUserToBug(int id)
        {
            var bug = _database.BugDatabase.Find(id);
            bug.AssignedToUser = User.Identity?.Name;
            bug.Status = "in work";

            _database.BugDatabase.Update(bug);
            _database.SaveChanges();

            return RedirectToAction("DetailedBugOverview", bug); //, id?
        }


    }
}

bugtracker/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using bugtracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace bugtracker.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            var roles = roleManager.Roles;
            ViewBag.CurrentRoles = roles;
            return View(roles);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RoleVerwaltung(Role role) //create new Role
        {
            IdentityRole identityRole = new IdentityRole
            {
                Name = role.RoleName
            };
            IdentityResult result =  await roleManager.CreateAsync(identityRole);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View(role);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost] //wieso userroles
        public async Task<IActionResult> GiveRoleToUser(List<UserRoles> model,string Id) //Parameter name "Id" has to be identical to asp-route-"Id", otherwise null
        {
            var role = await roleManager.FindByIdAsync(Id); 

            for (int i=0; i< model.Count ; i++ )
            {
                IdentityResult result = null;
                var user = await userManager.FindByIdAsync(model[i].UserId);

                if (model[i].Selected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!(model[i].Selected) && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }
                
                if (result.Succeeded) //why this
                {
                    if( i< model.Count - 1)
                    {
                        continue;
                    }
                    else return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index"); //wieso view -> null exc?
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> EditUsers(string Id)
        {
            var role = await roleManager.FindByIdAsync(Id);
            var users = userManager.Users;
            var model = new List<UserRoles>();

            ViewBag.CurrentRole = role;
            ViewData["Message"] = $"Edit {role.Name} Role";
            foreach (var user in userManager.Users)
            {
                var userRoles = new UserRoles
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoles.Selected = true;
                }
                else
                {
                    userRoles.Selected = false;
                }
                model.Add(userRoles);
            }
            return View(model);
        }

    }
}

bugtracker/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Page not found";
}

<h1>@ViewData["Title"]</h1>
<hr />

<h3><a asp-controller="Home" asp-action="Index"> Click here </a> to return to Homepage.</h3>

bugtracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bugtracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bugtracker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">simpleBT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle text-light" asp-area="" asp-controller="Bug" asp-action="Index" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Bugs
                          </a>
                          <ul class="dropdown-menu text-light" aria-labelledby="navbarScrollingDropdown">
                            <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Bug" asp-action="Index">open bugs</a></li>
                            <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Bug" asp-action="ClosedBugs">closed bugs</a></li>
                            <li><hr class="dropdown-divider text-dark"></li>
                            <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Bug" asp-action="BugHistory">bug history</a></li>
                          </ul>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - simpleBT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>